### ISSUE TITLE
newsAccessory is not defined

### ISSUE THREAD

**Issue by ghost** [cflurin/homebridge-punt#9]
[punt] Plugin - DidFinishLaunching
/usr/local/lib/node_modules/homebridge-punt/index.js:154
    newsAccessory.reachable = true;
    ^

ReferenceError: newsAccessory is not defined
    at PuntPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-punt/index.js:154:5)
    at PuntPlatform.addAccessories (/usr/local/lib/node_modules/homebridge-punt/index.js:141:12)
    at PuntPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-punt/index.js:96:12)
    at emitNone (events.js:72:20)
    at API.emit (events.js:166:7)
    at Server.str.replace.Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:98:13)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

-------

I can't get any of the local ports to connect and the terminal is throwing this error. Any idea how to fix this?

**Comment by cflurin** [comment]
@WTremml 
I don't use this plugin (FHEM) anymore. Maybe somebody else can help you or you migrate to https://www.npmjs.com/package/homebridge-mqtt

**Comment by cflurin** [comment]
@WTremml 
try changing line 154 in index.js:

>     newAccessory.reachable = true;
